package quanlydoannhanh;

import java.awt.HeadlessException;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.io.UnsupportedEncodingException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import quanlydoannhanh.SanPham;

public class HoaDon extends javax.swing.JInternalFrame {

    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    DefaultTableModel dtn = null;
    DefaultTableModel dtx = null;
    String datenow = null;

    /**
     * Creates new form tableSuaThongTin
     */
    public HoaDon() {
        initComponents();
        dtn = (DefaultTableModel) jTableHDNhap.getModel();
        dtx = (DefaultTableModel) jTableHDXuat.getModel();
        LocalDate localDate = LocalDate.now();
        datenow = DateTimeFormatter.ofPattern("yyyy/MM/dd").format(localDate);

        conn = JavaConnect.ConnectDB();
        updateTableHoaDonNhap();
        updateTableHoaDonXuat();

    }

    private void updateTableHoaDonNhap() {
        while (dtn.getRowCount() > 0) {
            dtn.removeRow(0);
        }
        String sql = "{call sp_AllHDN}";
        String row[] = new String[7];
        try {
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            while (rs.next()) {
                row[0] = rs.getString(1);
                row[1] = rs.getString(2);
                row[2] = rs.getString(3);
                row[3] = rs.getString(4);
                row[4] = rs.getString(5);
                row[5] = rs.getString(6);
                row[6] = rs.getString(7);
                dtn.addRow(row);
            }
        } catch (SQLException e) {
            JOptionPane.showConfirmDialog(null, e);
        }

    }

    private void updateTableHoaDonXuat() {
        while (dtx.getRowCount() > 0) {
            dtx.removeRow(0);
        }
        String sql = "{call sp_AllHDX}";
        String row[] = new String[7];
        try {
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            while (rs.next()) {
                row[0] = rs.getString(1);
                row[1] = rs.getString(2);
                row[2] = rs.getString(3);
                row[3] = rs.getString(4);
                row[4] = rs.getString(5);
                row[5] = rs.getString(6);
                row[6] = rs.getString(7);
                dtx.addRow(row);
            }
        } catch (SQLException e) {
            JOptionPane.showConfirmDialog(null, e);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        buttonGroupHDXuat = new javax.swing.ButtonGroup();
        buttonGroupHDNhap = new javax.swing.ButtonGroup();
        XuAT = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableHDXuat = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtGiaXuat = new javax.swing.JTextField();
        txtSoLuongXuat = new javax.swing.JTextField();
        jComboBoxMaThuocXuat = new javax.swing.JComboBox();
        jComboBoxMaKhachHangXuat = new javax.swing.JComboBox();
        txtMaHdXuat = new javax.swing.JTextField();
        jPanel17 = new javax.swing.JPanel();
        txtTimKiemHDXuat = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        btnThemXuat = new javax.swing.JButton();
        btnSuaXuat = new javax.swing.JButton();
        btnResetXuat = new javax.swing.JButton();
        btnXoaXuat = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableHDNhap = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        btnThemNhap = new javax.swing.JButton();
        btnXoaNhap = new javax.swing.JButton();
        btnSuaNhap = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtGiaNhap = new javax.swing.JTextField();
        jPanel18 = new javax.swing.JPanel();
        txtTimKiemHDNhap = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtSoLuongNhap = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxMaNhaCungCapNhap = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxMaThuocNhap = new javax.swing.JComboBox();
        txtMaHDNhap = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setTitle("Hóa Đơn");

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(986, 1000));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Danh sách hóa đơn xuất");

        jTableHDXuat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã hóa đơn", "Tên khách hàn", "Tên sản phẩm", "Số lượng", "Giá xuất", "Thành tiền", "Ngày xuất"
            }
        ));
        jTableHDXuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableHDXuatMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableHDXuat);

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setPreferredSize(new java.awt.Dimension(951, 600));

        jLabel16.setText("Giá xuất");

        jLabel15.setText("Số lượng");

        jLabel12.setText("Mã hóa đơn");

        jLabel13.setText("Khách hàng");

        jLabel14.setText("Sản Phẩm ");

        jComboBoxMaThuocXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxMaThuocXuatActionPerformed(evt);
            }
        });

        jPanel17.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tìm kiếm", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(153, 0, 153))); // NOI18N

        txtTimKiemHDXuat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTimKiemHDXuatKeyReleased(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/tkiem.PNG"))); // NOI18N
        jLabel8.setText("Mã hóa đơn");

        jButton2.setForeground(new java.awt.Color(0, 0, 204));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/mayin.PNG"))); // NOI18N
        jButton2.setText("In HĐX");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(txtTimKiemHDXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTimKiemHDXuat)
                    .addComponent(jLabel8)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Chức Năng", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(0, 0, 153))); // NOI18N

        btnThemXuat.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnThemXuat.setForeground(new java.awt.Color(0, 153, 0));
        btnThemXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/them1.png"))); // NOI18N
        btnThemXuat.setText("Thêm");
        btnThemXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemXuatActionPerformed(evt);
            }
        });

        btnSuaXuat.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSuaXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/sửa1.png"))); // NOI18N
        btnSuaXuat.setText("Sửa");
        btnSuaXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaXuatActionPerformed(evt);
            }
        });

        btnResetXuat.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnResetXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/reset1.png"))); // NOI18N
        btnResetXuat.setText("Reset");
        btnResetXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetXuatActionPerformed(evt);
            }
        });

        btnXoaXuat.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnXoaXuat.setForeground(new java.awt.Color(204, 0, 0));
        btnXoaXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/thunggiac2.png"))); // NOI18N
        btnXoaXuat.setText("Xóa");
        btnXoaXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaXuatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnThemXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(btnSuaXuat)
                .addGap(27, 27, 27)
                .addComponent(btnResetXuat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnXoaXuat)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThemXuat)
                    .addComponent(btnSuaXuat)
                    .addComponent(btnResetXuat)
                    .addComponent(btnXoaXuat))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtSoLuongXuat)
                    .addComponent(jComboBoxMaThuocXuat, 0, 257, Short.MAX_VALUE)
                    .addComponent(jComboBoxMaKhachHangXuat, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtMaHdXuat)
                    .addComponent(txtGiaXuat))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel17, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12)
                            .addComponent(txtMaHdXuat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel13)
                            .addComponent(jComboBoxMaKhachHangXuat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel14)
                            .addComponent(jComboBoxMaThuocXuat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel15)
                            .addComponent(txtSoLuongXuat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel16)
                            .addComponent(txtGiaXuat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(405, Short.MAX_VALUE))
        );

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/nhapt3.PNG"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 941, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel17)
                .addGap(101, 101, 101)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2)
                .addGap(163, 163, 163))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(372, 372, 372))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel17)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        XuAT.addTab("Hóa đơn xuất", jPanel1);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setPreferredSize(new java.awt.Dimension(1064, 1000));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 153, 255));
        jLabel10.setText("Danh sách hóa đơn nhập");

        jTableHDNhap.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã hóa đơn", "Nhà Cung Cấp", "Sản Phẩm", "Số Lượng", "Giá Nhập", "Thành Tiền", "Ngày Nhập"
            }
        ));
        jTableHDNhap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableHDNhapMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableHDNhap);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Chức Năng", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(102, 204, 0))); // NOI18N

        btnThemNhap.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnThemNhap.setForeground(new java.awt.Color(0, 204, 0));
        btnThemNhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/them1.png"))); // NOI18N
        btnThemNhap.setText("Thêm");
        btnThemNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemNhapActionPerformed(evt);
            }
        });

        btnXoaNhap.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnXoaNhap.setForeground(new java.awt.Color(255, 0, 0));
        btnXoaNhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/thunggiac2.png"))); // NOI18N
        btnXoaNhap.setText("Xóa");
        btnXoaNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaNhapActionPerformed(evt);
            }
        });

        btnSuaNhap.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSuaNhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/sửa1.png"))); // NOI18N
        btnSuaNhap.setText("Sửa");
        btnSuaNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaNhapActionPerformed(evt);
            }
        });

        btnReset.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/reset1.png"))); // NOI18N
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnThemNhap)
                .addGap(30, 30, 30)
                .addComponent(btnSuaNhap)
                .addGap(26, 26, 26)
                .addComponent(btnReset)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnXoaNhap)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThemNhap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSuaNhap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnReset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnXoaNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel10.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel11.setBackground(new java.awt.Color(204, 204, 204));

        jLabel6.setText("Giá nhập");

        txtGiaNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGiaNhapActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel6)
                .addGap(38, 38, 38)
                .addComponent(txtGiaNhap, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtGiaNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addContainerGap())
        );

        jPanel18.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tìm kiếm", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(204, 0, 0))); // NOI18N

        txtTimKiemHDNhap.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTimKiemHDNhapKeyReleased(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/tkiem.PNG"))); // NOI18N
        jLabel7.setText("Mã hóa đơn");

        jButton1.setForeground(new java.awt.Color(0, 51, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/mayin.PNG"))); // NOI18N
        jButton1.setText("In HĐ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtTimKiemHDNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtTimKiemHDNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        jLabel5.setText("Số lượng");

        txtSoLuongNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSoLuongNhapActionPerformed(evt);
            }
        });

        jLabel4.setText("Sản Phẩm");

        jLabel3.setText("Nhà cung cấp");

        jComboBoxMaThuocNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxMaThuocNhapActionPerformed(evt);
            }
        });

        txtMaHDNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaHDNhapActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(255, 153, 0));
        jLabel2.setText("Mã hóa đơn");

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/HoaDon.PNG"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jComboBoxMaNhaCungCapNhap, 0, 164, Short.MAX_VALUE)
                                .addComponent(txtMaHDNhap)))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(16, 16, 16)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addComponent(jLabel4))
                            .addGap(40, 40, 40)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jComboBoxMaThuocNhap, 0, 155, Short.MAX_VALUE)
                                .addComponent(txtSoLuongNhap))))
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addGap(31, 31, 31))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(148, 148, 148))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel10)
                .addGap(331, 331, 331))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(jLabel2))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(txtMaHDNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(42, 42, 42)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxMaNhaCungCapNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxMaThuocNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtSoLuongNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(205, 205, 205)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11)
                                .addComponent(jLabel18)))))
                .addContainerGap(274, Short.MAX_VALUE))
        );

        XuAT.addTab("Hóa đơn nhập", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(XuAT, javax.swing.GroupLayout.PREFERRED_SIZE, 991, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(151, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(XuAT, javax.swing.GroupLayout.DEFAULT_SIZE, 837, Short.MAX_VALUE)
                .addContainerGap())
        );

        setBounds(0, 0, 1168, 771);
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemNhapActionPerformed
        if (txtMaHDNhap.getText().length() == 0) {
            JOptionPane.showMessageDialog(null, "Chưa nhập mã nhập");
        } else if (txtGiaNhap.getText().length() == 0) {
            JOptionPane.showMessageDialog(null, "Chưa nhập giá");
        } else if (txtSoLuongNhap.getText().length() == 0) {
            JOptionPane.showMessageDialog(null, "Chưa nhập số lượng");
        } else if (ExceptionString.isNumber(txtGiaNhap.getText()) == false) {
            JOptionPane.showMessageDialog(null, "Giá nhập phải là 1 số");
        } else if (ExceptionString.isNumber(txtSoLuongNhap.getText()) == false) {
            JOptionPane.showMessageDialog(null, "số lượng nhập phải là 1 số");
        } else {
            try {
                if (ExceptionString.isUnicode(txtMaHDNhap.getText())) {
                    JOptionPane.showMessageDialog(null, "Mã HD không chứa kí tự đặc biệt");
                } else if (ExceptionString.isSpace(txtMaHDNhap.getText())) {
                    JOptionPane.showMessageDialog(null, "Mã HD không khoảng trắng");
                } else {
                    try {
                        int tt = Integer.parseInt(txtSoLuongNhap.getText()) * Integer.parseInt(txtGiaNhap.getText());
                        DisplayValueModel dvm = (DisplayValueModel) jComboBoxMaThuocNhap.getSelectedItem();
                        DisplayValueModel dvmncc = (DisplayValueModel) jComboBoxMaNhaCungCapNhap.getSelectedItem();
                        String sql = "Insert into  HoaDonNhap(MaHDN, MaSP, MaNCC, SoLuong, ThanhTien, NgayNhap, GiaNhap) values (?,?,?,?,?,CONVERT(DATETIME,?, 102),?)";

                        pst = conn.prepareStatement(sql);

                        pst.setString(1, txtMaHDNhap.getText());
                        pst.setString(2, dvm.valueMember.toString());
                        pst.setString(3, dvmncc.valueMember.toString());
                        pst.setString(4, txtSoLuongNhap.getText());

                        pst.setString(7, txtGiaNhap.getText());
                        pst.setString(5, String.valueOf(tt));
                        pst.setString(6, datenow);
                        int i = pst.executeUpdate();
                        if (i > 0) {
                            JOptionPane.showMessageDialog(null, "Lưu thành công");
                            cleanN();
                        } else {
                            JOptionPane.showMessageDialog(null, "Lưu thất bại");
                        }

                    } catch (SQLException | HeadlessException e) {
                        JOptionPane.showMessageDialog(null, e);
                    }
                    updateTableHoaDonNhap();
                }
            } catch (UnsupportedEncodingException ex) {
                Logger.getLogger(NhaCungCap.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    /*               
    }//GEN-LAST:event_btnThemNhapActionPerformed
*/

    private void btnSuaNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaNhapActionPerformed
        DisplayValueModel dvm = (DisplayValueModel) jComboBoxMaThuocNhap.getSelectedItem();
        DisplayValueModel dvmncc = (DisplayValueModel) jComboBoxMaNhaCungCapNhap.getSelectedItem();
         if (txtMaHDNhap.getText().length() == 0) {
            JOptionPane.showMessageDialog(null, "Chọn dòng cần sửa");
         }
          else if (txtGiaNhap.getText().length() == 0) {
            JOptionPane.showMessageDialog(null, "Chưa nhập giá");
                  
        } else if (txtSoLuongNhap.getText().length() == 0) {
            JOptionPane.showMessageDialog(null, "Chưa nhập số lượng");
        } else if (ExceptionString.isNumber(txtGiaNhap.getText()) == false) {
            JOptionPane.showMessageDialog(null, "Giá nhập phải là 1 số");
        } else if (ExceptionString.isNumber(txtSoLuongNhap.getText()) == false) {
            JOptionPane.showMessageDialog(null, "số lượng nhập phải là 1 số");
        } else {
            try {
                String value0 = txtMaHDNhap.getText();
                String value1 = dvmncc.valueMember.toString();
                String value2 = dvm.valueMember.toString();
                String value3 = txtSoLuongNhap.getText();
                String value4 = txtGiaNhap.getText();

                String sql = "update HoaDonNhap set MaNCC =? , MaSP =?, SoLuong =?, ThanhTien =(SoLuong*ThanhTien), GiaNhap =? where MaHDN=?";

                pst = conn.prepareStatement(sql);
                pst.setString(1, value1);
                pst.setString(2, value2);
                pst.setString(3, value3);
                pst.setString(4, value4);
                pst.setString(5, value0);
                pst.execute();
                JOptionPane.showMessageDialog(null, "Sửa thành công");
                cleanN();
            } catch (SQLException | HeadlessException e) {
                JOptionPane.showMessageDialog(null, "Sửa thất bại");
            }
            updateTableHoaDonNhap();
        }

    }//GEN-LAST:event_btnSuaNhapActionPerformed

    private void btnXoaNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaNhapActionPerformed
        int p = JOptionPane.showConfirmDialog(null, "Bạn chắc chắn muốn xóa", "Xóa", JOptionPane.YES_NO_OPTION);
        if (p == 0) {
            String sql = "delete from HoaDonNhap where MaHDN =?";
            try {
                pst = conn.prepareStatement(sql);
                pst.setString(1, txtMaHDNhap.getText());
                pst.execute();
                JOptionPane.showMessageDialog(null, "Xóa thành công");
                cleanN();
            } catch (SQLException | HeadlessException e) {
                JOptionPane.showMessageDialog(null, "Xóa thất bại");
            }
            updateTableHoaDonNhap();
        }
    }//GEN-LAST:event_btnXoaNhapActionPerformed

    private void btnThemXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemXuatActionPerformed
        if (txtMaHdXuat.getText().length() == 0) {
            JOptionPane.showMessageDialog(null, "Chưa nhập mã xuất");
        } else if (txtGiaXuat.getText().length() == 0) {
            JOptionPane.showMessageDialog(null, "Chưa nhập giá");
        } else if (txtSoLuongXuat.getText().length() == 0) {
            JOptionPane.showMessageDialog(null, "Chưa nhập số lượng");
        } else if (ExceptionString.isNumber(txtGiaXuat.getText()) == false) {
            JOptionPane.showMessageDialog(null, "Giá nhập phải là 1 số");
        } else if (ExceptionString.isNumber(txtSoLuongXuat.getText()) == false) {
            JOptionPane.showMessageDialog(null, "số lượng nhập phải là 1 số");
        } else {
            try {
                if (ExceptionString.isUnicode(txtMaHdXuat.getText())) {
                    JOptionPane.showMessageDialog(null, "Mã HD không chứa kí tự đặc biệt");
                } else if (ExceptionString.isSpace(txtMaHdXuat.getText())) {
                    JOptionPane.showMessageDialog(null, "Mã HD không khoảng trắng");
                } else {
                    try {
                        int tt = Integer.parseInt(txtSoLuongXuat.getText()) * Integer.parseInt(txtGiaXuat.getText());
                        DisplayValueModel dvm = (DisplayValueModel) jComboBoxMaThuocXuat.getSelectedItem();
                        DisplayValueModel dvmkh = (DisplayValueModel) jComboBoxMaKhachHangXuat.getSelectedItem();
                        String sql = "Insert into  HoaDonXuat (MaHDX, MaKH, MaSP, SoLuong, DonGia, NgayXuat, ThanhTien) values (?,?,?,?,?,CONVERT(DATETIME,?, 102),?)";

                        pst = conn.prepareStatement(sql);
                        pst.setString(1, txtMaHdXuat.getText());
                        pst.setString(2, dvmkh.valueMember.toString());
                        pst.setString(3, dvm.valueMember.toString());
                        pst.setString(4, txtSoLuongXuat.getText());
                        pst.setString(5, txtGiaXuat.getText());
                        pst.setString(7, String.valueOf(tt));
                        pst.setString(6, datenow);
                        int i = pst.executeUpdate();
                        if (i > 0) {
                            JOptionPane.showMessageDialog(null, "Lưu thành công");
                            cleanX();
                        } else {
                            JOptionPane.showMessageDialog(null, "Lưu thất bại");
                        }

                    } catch (SQLException | HeadlessException e) {
                        JOptionPane.showMessageDialog(null, "Số Lượng Vượt Quá Trong Kho");
                    }
                    updateTableHoaDonXuat();
                }
            } catch (UnsupportedEncodingException ex) {
                Logger.getLogger(NhaCungCap.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_btnThemXuatActionPerformed

    private void btnSuaXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaXuatActionPerformed
        if (txtMaHdXuat.getText().length() == 0) {
            JOptionPane.showMessageDialog(null, "Chọn dòng cần sửa");
         }
        else if (txtGiaXuat.getText().length() == 0) {
            JOptionPane.showMessageDialog(null, "Chưa nhập giá");
        } else if (txtSoLuongXuat.getText().length() == 0) {
            JOptionPane.showMessageDialog(null, "Chưa nhập số lượng");
        } else if (ExceptionString.isNumber(txtGiaXuat.getText()) == false) {
            JOptionPane.showMessageDialog(null, "Giá nhập phải là 1 số");
        } else if (ExceptionString.isNumber(txtSoLuongXuat.getText()) == false) {
            JOptionPane.showMessageDialog(null, "số lượng nhập phải là 1 số");
        } else {
            try {
                DisplayValueModel dvm = (DisplayValueModel) jComboBoxMaThuocXuat.getSelectedItem();
                DisplayValueModel dvmkh = (DisplayValueModel) jComboBoxMaKhachHangXuat.getSelectedItem();
                String value0 = txtMaHdXuat.getText();
                String value1 = dvmkh.valueMember.toString();
                String value2 = dvm.valueMember.toString();
                String value3 = txtSoLuongXuat.getText();
                String value4 = txtGiaXuat.getText();
                String sql = "update HoaDonXuat set MaKH =? , MaSP =?, SoLuong =?, ThanhTien =(SoLuong*DonGia), DonGia =? where MaHDX=?";
                pst = conn.prepareStatement(sql);
                pst.setString(1, value1);
                pst.setString(2, value2);
                pst.setString(3, value3);
                pst.setString(4, value4);
                pst.setString(5, value0);
                pst.execute();
                JOptionPane.showMessageDialog(null, "Sửa thành công");
                cleanX();
            } catch (SQLException | HeadlessException e) {
                JOptionPane.showMessageDialog(null, "Sửa thất bại");
            }
            updateTableHoaDonXuat();
        }

    }//GEN-LAST:event_btnSuaXuatActionPerformed

    private void btnXoaXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaXuatActionPerformed
        int p = JOptionPane.showConfirmDialog(null, "Bạn chắc chắn muốn xóa", "Xóa", JOptionPane.YES_NO_OPTION);
        if (p == 0) {
            String sql = "delete from HoaDonXuat where MaHDX =?";
            try {
                pst = conn.prepareStatement(sql);
                pst.setString(1, txtMaHdXuat.getText());
                pst.execute();
                JOptionPane.showMessageDialog(null, "Xóa thành công");
                cleanX();
            } catch (SQLException | HeadlessException e) {
                JOptionPane.showMessageDialog(null, "Xóa thất bại");
            }
            updateTableHoaDonXuat();
        }
    }//GEN-LAST:event_btnXoaXuatActionPerformed

    private void txtTimKiemHDXuatKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimKiemHDXuatKeyReleased
        while (dtx.getRowCount() > 0) {
            dtx.removeRow(0);
        }
        String sql = "select * from HoaDonXuat where MaHDX=?";
        String row[] = new String[7];
        try {
            pst = conn.prepareStatement(sql);
            pst.setString(1, txtTimKiemHDXuat.getText());
            rs = pst.executeQuery();
            if (rs.next()) {

                row[0] = rs.getString(1);
                row[1] = rs.getString(2);
                row[2] = rs.getString(3);
                row[3] = rs.getString(4);
                row[4] = rs.getString(5);
                row[5] = rs.getString(6);
                row[6] = rs.getString(7);
                dtx.addRow(row);
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Thất bại");
        }
    }//GEN-LAST:event_txtTimKiemHDXuatKeyReleased

    private void txtTimKiemHDNhapKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimKiemHDNhapKeyReleased
        while (dtn.getRowCount() > 0) {
            dtn.removeRow(0);
        }
        String sql = "select * from HoaDonNhap where MaHDN=?";
        String row[] = new String[7];
        try {
            pst = conn.prepareStatement(sql);
            pst.setString(1, txtTimKiemHDNhap.getText());
            rs = pst.executeQuery();
            if (rs.next()) {

                row[0] = rs.getString(1);
                row[1] = rs.getString(2);
                row[2] = rs.getString(3);
                row[3] = rs.getString(4);
                row[4] = rs.getString(5);
                row[5] = rs.getString(6);
                row[6] = rs.getString(7);
                dtn.addRow(row);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Thất bại");
        }
    }//GEN-LAST:event_txtTimKiemHDNhapKeyReleased
    private void cleanN() {
        txtMaHDNhap.setText("");
        txtSoLuongNhap.setText("");
        txtGiaNhap.setText("");
        txtMaHDNhap.enable(true);
    }

    private void cleanX() {
        txtMaHdXuat.setText("");
        txtSoLuongXuat.setText("");
        txtGiaXuat.setText("");
        txtMaHdXuat.enable(true);
    }
    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed

        cleanN();
        updateTableHoaDonNhap();
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnResetXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetXuatActionPerformed

        cleanX();
        updateTableHoaDonXuat();
    }//GEN-LAST:event_btnResetXuatActionPerformed

    private void jTableHDNhapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableHDNhapMouseClicked
        // TODO add your handling code here:
        int row = jTableHDNhap.rowAtPoint(evt.getPoint());
        txtMaHDNhap.setText(jTableHDNhap.getValueAt(row, 0).toString());
        jComboBoxMaNhaCungCapNhap.setSelectedItem(jTableHDNhap.getValueAt(row, 1).toString());
        jComboBoxMaThuocNhap.setSelectedItem(jTableHDNhap.getValueAt(row, 2).toString());
        txtSoLuongNhap.setText(jTableHDNhap.getValueAt(row, 3).toString());
        txtGiaNhap.setText(jTableHDNhap.getValueAt(row, 4).toString());
        txtMaHDNhap.enable(false);
    }//GEN-LAST:event_jTableHDNhapMouseClicked

    private void jTableHDXuatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableHDXuatMouseClicked
        // TODO add your handling code here:
        int row = jTableHDXuat.rowAtPoint(evt.getPoint());
        txtMaHdXuat.setText(jTableHDXuat.getValueAt(row, 0).toString());
        jComboBoxMaKhachHangXuat.setSelectedItem(jTableHDXuat.getValueAt(row, 1).toString());
        jComboBoxMaThuocNhap.setSelectedItem(jTableHDXuat.getValueAt(row, 2).toString());
        txtSoLuongXuat.setText(jTableHDXuat.getValueAt(row, 3).toString());
        txtGiaXuat.setText(jTableHDXuat.getValueAt(row, 4).toString());
        txtMaHdXuat.enable(false);
    }//GEN-LAST:event_jTableHDXuatMouseClicked

    private void txtMaHDNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaHDNhapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaHDNhapActionPerformed

    private void jComboBoxMaThuocNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxMaThuocNhapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxMaThuocNhapActionPerformed

    private void txtSoLuongNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSoLuongNhapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSoLuongNhapActionPerformed

    private void txtGiaNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGiaNhapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGiaNhapActionPerformed

    private void jComboBoxMaThuocXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxMaThuocXuatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxMaThuocXuatActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
  
            try {
                
                FileWriter fw;
                fw = new FileWriter("InHoaDonXuat.txt");
                try (BufferedWriter bw = new BufferedWriter(fw)) {
                    bw.write("\t\t\t\t\t\tHóa Đơn Xuất" + "\n");
                    bw.write("Mã HĐ\t\t" + "Tên KH\t\t" + "Sản Phẩm\t\t"+"Số Lượng\t\t"+"Giá Xuất\t"
                            + "Thành Tiền\t" + "Ngày Xuất" + "\n");
                    for (int i = 0; i < jTableHDXuat.getRowCount(); i++) {
                        for (int j = 0; j < jTableHDXuat.getColumnCount(); j++) {
                            bw.write(jTableHDXuat.getValueAt(i, j).toString() + "\t\t");
                        }
                        bw.newLine();
                    }
                    JOptionPane.showMessageDialog(rootPane, "In HĐX thành công!");
                }
                fw.close();
            } catch (HeadlessException | IOException e) {
                JOptionPane.showMessageDialog(rootPane, "Lỗi!");
            }
              
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
                
                FileWriter fw;
                fw = new FileWriter("InHoaDonNhap.txt");
                try (BufferedWriter bw = new BufferedWriter(fw)) {
                     bw.write("\t\t\t\t\t\tHóa Đơn Nhập" + "\n");
                    bw.write("Mã HĐ\t\t" + "Nhà CC\t\t" + "Sản Phẩm\t\t"+"Số Lượng\t\t"+"Giá Nhập\t"
                            + "Thành Tiền\t" + "Ngày Nhập" + "\n");
                    for (int i = 0; i < jTableHDNhap.getRowCount(); i++) {
                        for (int j = 0; j < jTableHDNhap.getColumnCount(); j++) {
                            bw.write(jTableHDNhap.getValueAt(i, j).toString() + "\t\t");
                        }
                        bw.newLine();
                    }
                    JOptionPane.showMessageDialog(rootPane, "In HĐN thành công!");
                }
                fw.close();
            } catch (HeadlessException | IOException e) {
                JOptionPane.showMessageDialog(rootPane, "Lỗi!");
            }
    }//GEN-LAST:event_jButton1ActionPerformed

    public void fillComboMaThuoc() {
        DefaultComboBoxModel dcb = new DefaultComboBoxModel();
        try {
            String sql = "Select * from SanPham";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            while (rs.next()) {
                String maThuoc = rs.getString("MaSP");
                String tenThuoc = rs.getString("TenSP");
                DisplayValueModel dvn = new DisplayValueModel(tenThuoc, maThuoc);
                dcb.addElement(dvn);
            }
            jComboBoxMaThuocNhap.setModel(dcb);
            jComboBoxMaThuocXuat.setModel(dcb);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    public void fillComboMaNhaCungCapNhap() {
        String sql = "Select * from NhaCungCap";
        DefaultComboBoxModel dcb = new DefaultComboBoxModel();
        try {
            pst = conn.prepareCall(sql);
            rs = pst.executeQuery();
            while (rs.next()) {
                String tenNhaCungCap = rs.getString("TenNhaCC");
                String maNhaCungCap = rs.getString("MaNCC");
                DisplayValueModel dvn = new DisplayValueModel(tenNhaCungCap, maNhaCungCap);
                dcb.addElement(dvn);
            }
            jComboBoxMaNhaCungCapNhap.setModel(dcb);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    public void fillComboMaKhachHangXuat() {
        DefaultComboBoxModel dcb = new DefaultComboBoxModel();
        String sql = "Select * from KhachHang";
        try {
            pst = conn.prepareCall(sql);
            rs = pst.executeQuery();
            while (rs.next()) {
                String tenKH = rs.getString("TenKH");
                String maKH = rs.getString("MaKH");
                DisplayValueModel dvn = new DisplayValueModel(tenKH, maKH);
                dcb.addElement(dvn);
            }
            jComboBoxMaKhachHangXuat.setModel(dcb);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane XuAT;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnResetXuat;
    private javax.swing.JButton btnSuaNhap;
    private javax.swing.JButton btnSuaXuat;
    private javax.swing.JButton btnThemNhap;
    private javax.swing.JButton btnThemXuat;
    private javax.swing.JButton btnXoaNhap;
    private javax.swing.JButton btnXoaXuat;
    private javax.swing.ButtonGroup buttonGroupHDNhap;
    private javax.swing.ButtonGroup buttonGroupHDXuat;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBoxMaKhachHangXuat;
    private javax.swing.JComboBox jComboBoxMaNhaCungCapNhap;
    private javax.swing.JComboBox jComboBoxMaThuocNhap;
    private javax.swing.JComboBox jComboBoxMaThuocXuat;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableHDNhap;
    private javax.swing.JTable jTableHDXuat;
    private javax.swing.JTextField txtGiaNhap;
    private javax.swing.JTextField txtGiaXuat;
    private javax.swing.JTextField txtMaHDNhap;
    private javax.swing.JTextField txtMaHdXuat;
    private javax.swing.JTextField txtSoLuongNhap;
    private javax.swing.JTextField txtSoLuongXuat;
    private javax.swing.JTextField txtTimKiemHDNhap;
    private javax.swing.JTextField txtTimKiemHDXuat;
    // End of variables declaration//GEN-END:variables

}
