/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GoiMon;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import quanlydoannhanh.DisplayValueModel;
import quanlydoannhanh.JavaConnect;

/**
 *
 * @author admin135
 */
public class GoiMon extends javax.swing.JFrame {
    Connection connHD = null;
    Connection conn = null;
    ResultSet rsHoiDap = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    DefaultTableModel dtHoiDap = null;
    PreparedStatement pstHoiDap = null;
    String datenow = null;
    DefaultComboBoxModel dcb = null;
    /**
     * Creates new form GoiMon
     */
    public GoiMon() {
        initComponents();
        setTitle("Gọi món");
        setLocationRelativeTo(null);
        LocalDate localDate = LocalDate.now();
        datenow = DateTimeFormatter.ofPattern("yyyy/MM/dd").format(localDate);
        connHD = JavaConnect.ConnectDB();
        conn = JavaConnect.ConnectDB();
        dtHoiDap = (DefaultTableModel) jTableGoiMon.getModel();
        dcb = new DefaultComboBoxModel();
        fillComboxTaiKhoan();
        updateTableHoiDap();
    }

    private void updateTableHoiDap() {
        //throw new UnsupportedOperationException("Not supported yet."); 
         while (dtHoiDap.getRowCount() > 0) {
            dtHoiDap.removeRow(0);
        }
        String sql = "Select SanPham.MaSP,SanPham.TenSP,GoiMon.NgayGoi from GoiMon INNER JOIN SanPham ON"
                + " SanPham.MaSP = GoiMon.MaSP"
                 ;
        String row[] = new String[3];
        try {
            pstHoiDap = connHD.prepareStatement(sql);
            rsHoiDap = pstHoiDap.executeQuery();
            while (rsHoiDap.next()) {
                row[1] = rsHoiDap.getString(1);
                row[0] = rsHoiDap.getString(2);
                row[2] = rsHoiDap.getString(3);
                dtHoiDap.addRow(row);
            }
        } catch (SQLException e) {
            JOptionPane.showConfirmDialog(null, e);
        }

    }
 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnChon = new javax.swing.JButton();
        btnHuyChon = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnThoat = new javax.swing.JButton();
        jComboBoxTimKiem = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableGoiMon = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtKH = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gọi món");

        jLabel1.setText("Tìm kiếm món");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 102, 255));
        jLabel9.setText("Gọi món ");

        btnChon.setText("Chọn>>");
        btnChon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChonActionPerformed(evt);
            }
        });

        btnHuyChon.setText("<<Hủy chọn");
        btnHuyChon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyChonActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Danh sách món vừa chọn");

        btnThoat.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        jTableGoiMon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Tên Sản phẩm", "Mã Sản Phẩm", "Ngày"
            }
        ));
        jTableGoiMon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableGoiMonMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableGoiMon);

        jLabel2.setText("Mã ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(73, 73, 73)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jComboBoxTimKiem, 0, 237, Short.MAX_VALUE)
                                    .addComponent(txtKH))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnChon, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnHuyChon, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(17, 17, 17)))))
                .addContainerGap(34, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(227, 227, 227)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBoxTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnChon, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnHuyChon, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67)
                        .addComponent(btnThoat))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(74, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
       this.dispose();
    }//GEN-LAST:event_btnThoatActionPerformed

    private void btnChonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChonActionPerformed
        DisplayValueModel dvm = (DisplayValueModel) jComboBoxTimKiem.getSelectedItem();
        String KH = txtKH.getText();
        if(txtKH.getText().length() == 0){
            JOptionPane.showConfirmDialog(null, "Chưa nhập mã sản phẩm","Message",JOptionPane.ERROR_MESSAGE);
        }
        else{
            try {
                String sql = "Insert into GoiMon(MaSP, TenSP,NgayGoi) values (?,?,CONVERT(DATETIME,?, 102))";
                pstHoiDap = connHD.prepareStatement(sql);
                pstHoiDap.setString(3, datenow);
                pstHoiDap.setString(1, KH);
                pstHoiDap.setString(2, dvm.valueMember.toString());
                pstHoiDap.execute();
                JOptionPane.showMessageDialog(null, "Lưu thành công");
                txtKH.setText("");
                //clean();
            } catch (SQLException | HeadlessException e) {
                JOptionPane.showMessageDialog(null, "Mã bị trùng" + e);
            }
            updateTableHoiDap();
  
        }

    }//GEN-LAST:event_btnChonActionPerformed

    private void btnHuyChonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyChonActionPerformed
        int p = JOptionPane.showConfirmDialog(null, "Bạn chắc chắn muốn hủy", "Xóa", JOptionPane.YES_NO_OPTION);
        if (p == 0) {
            String sql = "delete from GoiMon where MaSP =?";
            try {
                pstHoiDap = connHD.prepareStatement(sql);
                pstHoiDap.setString(1, txtKH.getText());
                pstHoiDap.execute();
                JOptionPane.showMessageDialog(null, "Xóa thành công");
                clean();
            } catch (HeadlessException | SQLException e) {
                JOptionPane.showMessageDialog(this, "Xóa thất bại" + e);
            }
            updateTableHoiDap();
        }
    }//GEN-LAST:event_btnHuyChonActionPerformed

    private void jTableGoiMonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableGoiMonMouseClicked
        int row = jTableGoiMon.getSelectedRow();
        jComboBoxTimKiem.setSelectedItem(jTableGoiMon.getValueAt(row, 0).toString());
        txtKH.setText(jTableGoiMon.getModel().getValueAt(row, 1).toString());
        txtKH.enable(false);
    }//GEN-LAST:event_jTableGoiMonMouseClicked

    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChon;
    private javax.swing.JButton btnHuyChon;
    private javax.swing.JButton btnThoat;
    private javax.swing.JComboBox<String> jComboBoxTimKiem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableGoiMon;
    private javax.swing.JTextField txtKH;
    // End of variables declaration//GEN-END:variables

    private void fillComboxTaiKhoan() {
        String sql = "Select SanPham.TenSP from SanPham";
        try {
            pst = conn.prepareCall(sql);
            rs = pst.executeQuery();
            while (rs.next()) {
                String tenSP = rs.getString("TenSP");
                String maSP = rs.getString("TenSP");
                DisplayValueModel dvn = new DisplayValueModel(tenSP,maSP);
                dcb.addElement(dvn);
            }
            jComboBoxTimKiem.setModel(dcb);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    private void clean() {
        txtKH.setText("");
        jComboBoxTimKiem.setSelectedItem(true);
        txtKH.enable(true);
    }


}

